#!/bin/bash

# Convenient 'ls' abbreviations
alias l.="ls -d .*"
alias sl="ls"
alias ll="ls -l"
alias lla="ls -al"

# Convenient 'git' abbreviations
alias add="git add"
alias commit="git commit"
alias status="git status"
alias atag="git tag -s"

# Typing 'mpv' is so inconvenient...
alias m='mpv'

# Finds all the git repos on the system
# Not sure why I have this, but it's kinda cool.
alias repos='find / -name ".git" -type d 2>/dev/null'

# Runs emacs in terminal mode
alias e="emacs -nw"

# Pretty-prints non-optimized core from GHC
# Requires ghc-core executable to be installed from e.g., Hackage
alias pretty-core="ghc-core --no-asm --no-cast -- -dsuppress-var-kinds -dsuppress-type-applications -dsuppress-uniques"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


# BEST ALIAS EVER
alias fucking='sudo'
