#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

if [ -f /etc/profile ]; then
    . /etc/profile
fi

# mutt background fix
# COLORFGBG="default;default"

# User specific aliases and functions
PATH=${HOME}/.local/bin:$PATH
export PATH

# TeX setup
export TEXINPUTS=".:$HOME/Documents/latex/:"
export BIBINPUTS=".:$HOME/Documents/bibtex/:"

# Sets the current terminal as GPG's output interface
GPG_TTY=$(tty)
export GPG_TTY

# Show the currently running command in the terminal title:
# http://www.davidpashley.com/articles/xterm-titles-with-bash.html
show_command_in_title_bar()
{
    case "$BASH_COMMAND" in
        *\033]0*)
            # The command is trying to set the title bar as well;
            # this is most likely the execution of $PROMPT_COMMAND.
            # In any case nested escapes confuse the terminal, so don't
            # output them.
            ;;
        *)
            echo -ne "\033]0;${USER}@${HOSTNAME%%.*}: ${BASH_COMMAND}\007"
            ;;
    esac
}

# Commented because it breaks something. Not sure what any more.
#trap show_command_in_title_bar DEBUG;

# SCIPY's image viewer should be my preferred image viewer (Eye of Gnome)
export SCIPY_PIL_IMAGE_VIEWER=eog

# Defines key locations for awscli
export EC2_PRIVATE_KEY=~/.ssh/pk-UY653PEPKS5XTNDA7NO27TR4SONMZ2SW.pem
export EC2_CERT=~/.ssh/cert-UY653PEPKS5XTNDA7NO27TR4SONMZ2SW.pem

. ${HOME}/.bash_alias
. ${HOME}/.bash_cd
. ${HOME}/.bash_haskell
. ${HOME}/.bash_prompt
. ${HOME}/.bash_wine
. ${HOME}/.bash_completion
