#!/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Tell me about my current goals
runhaskell ~/.local/bin/Goals.hs < ~/.goals

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# mutt background fix
# COLORFGBG="default;default"

# User specific aliases and functions
PATH=${HOME}/.local/bin:$PATH
export PATH

EDITOR=emacs
export EDITOR

# TeX setup
export TEXINPUTS=".:$HOME/Documents/latex/:"
export BIBINPUTS=".:$HOME/Documents/bibtex/:"

# Sets the current terminal as GPG's output interface
GPG_TTY=$(tty)
export GPG_TTY

# Show the currently running command in the terminal title:
# http://www.davidpashley.com/articles/xterm-titles-with-bash.html
show_command_in_title_bar()
{
    case "$BASH_COMMAND" in
        *\033]0*)
            # The command is trying to set the title bar as well;
            # this is most likely the execution of $PROMPT_COMMAND.
            # In any case nested escapes confuse the terminal, so don't
            # output them.
            ;;
        *)
            echo -ne "\033]0;${USER}@${HOSTNAME%%.*}: ${BASH_COMMAND}\007"
            ;;
    esac
}

# Commented because it breaks something. Not sure what any more.
#trap show_command_in_title_bar DEBUG;

# SCIPY's image viewer should be my preferred image viewer (Eye of Gnome)
export SCIPY_PIL_IMAGE_VIEWER=eog

# Defines key locations for awscli
export EC2_PRIVATE_KEY=~/.ssh/pk-UY653PEPKS5XTNDA7NO27TR4SONMZ2SW.pem
export EC2_CERT=~/.ssh/cert-UY653PEPKS5XTNDA7NO27TR4SONMZ2SW.pem

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

. ${HOME}/.bash_alias
. ${HOME}/.bash_cd
. ${HOME}/.bash_haskell
. ${HOME}/.bash_prompt
. ${HOME}/.bash_wine
. ${HOME}/.bash_less
. ${HOME}/.bash_dircolors
. ${HOME}/.bash_limbo
