# Set up the desktop background
hsetroot -fill ~/Pictures/archived_pics/Konachan.com\ -\ 151824\ benitama\ landscape\ moriya_suwako\ scenic\ touhou\ water\ waterfall.jpg

# Sets up Dell XPS 1640 volume keys
xbindkeys

# Makes sure the cursor doesn't look weird as much as possible.
xsetroot -cursor_name left_ptr

# Sets up compose key and, optionally, Dvorak layout.
setxkbmap -option compose:menu #-layout dvorak

# Sets up terminal colors
xrdb ~/.Xresources

# Starts RXVT-unicode as a terminal server This dramatically reduces the
# resource usage of URXVT, though it does mean all the terminals crash when
# URXVT goes down.
urxvtd -q -f -o

# Make the terminals pretty (enables transparency)
xcompmgr &

# Mutt setup stuff, not currently in use
#sh ~/.mutt/notify.sh &
#~/.cabal/bin/arbtt-capture &

# Fork to xmonad
exec xmonad
